name: Build docker and deploy

on:
  push:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Docker images
        run: |
          docker build . -t yahkerobertkertasnya/portfolio:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push yahkerobertkertasnya/portfolio:latest

  pull-and-deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd portfolio
            git pull
            docker compose -f docker-compose.server.yml pull
            docker compose -f docker-compose.server.yml down
            docker compose -f docker-compose.server.yml up -d
            docker image prune -f